name: continuous

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Quality Gates
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: npm ci
      - name: Lint All Packages
        run: npm run lint
      - name: Build All Packages
        run: npm run build
      - name: Verify Bundle Sizes
        run: npm run verify:bundle-size
      - name: Test All Packages
        run: npm run test:coverage
      - name: Upload Hls-Parser Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: hls-parser
          files: ./packages/hls-parser/coverage/coverage-final.json
          name: hls-parser-coverage
          fail_ci_if_error: true
      - name: Upload Dash-Parser Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: dash-parser
          files: ./packages/dash-parser/coverage/coverage-final.json
          name: dash-parser-coverage
          fail_ci_if_error: true
      - name: Upload Player Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: playback
          files: ./packages/playback/coverage/coverage-final.json
          name: playback-coverage
          fail_ci_if_error: true
