name: "limit-size"
on:
  pull_request:
    branches:
      - main
jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # install node version from .nvmrc
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      # install deps
      - name: Install Dependencies
        run: npm ci

      # build all packages
      - name: Build All Packages
        run: npm run build

      - name: Size Limit Json
        uses: andresz1/size-limit-action@v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_step: build
          script: npm run size-limit:json
